@echo off
echo Installing dependencies and starting AI Academy Server...
cd /d %~dp0
call .venv\Scripts\activate.bat
echo Installing dependencies from requirements.txt...
pip install -r requirements.txt
echo Starting server...
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
